# Generated by Django 5.2.7 on 2025-10-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_article_author'),
    ]

    operations = [
    ]
